// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odzagbhwjbphufqgcray.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kemFnYmh3amJwaHVmcWdjcmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjYyMDAsImV4cCI6MjA2NzE0MjIwMH0.gYcMJgQ0b5EVAkLfoABtquIN2mJjLk2UrBrzf_WyKto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});